// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// JWTKey is an object representing the database table.
type JWTKey struct {
	// Key ID (used in JWT header)
	Kid string `boil:"kid" json:"kid" toml:"kid" yaml:"kid"`
	// RSA private key (encrypted with AES-256-GCM)
	PrivateKey string `boil:"private_key" json:"private_key" toml:"private_key" yaml:"private_key"`
	// RSA public key (exposed via JWKS endpoint)
	PublicKey string `boil:"public_key" json:"public_key" toml:"public_key" yaml:"public_key"`
	// Key status: active (signing new tokens), rotating (grace period), retired (no longer used)
	Status    string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ExpiresAt null.Time `boil:"expires_at" json:"expires_at,omitempty" toml:"expires_at" yaml:"expires_at,omitempty"`
	RetiredAt null.Time `boil:"retired_at" json:"retired_at,omitempty" toml:"retired_at" yaml:"retired_at,omitempty"`

	R *jwtKeyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L jwtKeyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var JWTKeyColumns = struct {
	Kid        string
	PrivateKey string
	PublicKey  string
	Status     string
	CreatedAt  string
	ExpiresAt  string
	RetiredAt  string
}{
	Kid:        "kid",
	PrivateKey: "private_key",
	PublicKey:  "public_key",
	Status:     "status",
	CreatedAt:  "created_at",
	ExpiresAt:  "expires_at",
	RetiredAt:  "retired_at",
}

var JWTKeyTableColumns = struct {
	Kid        string
	PrivateKey string
	PublicKey  string
	Status     string
	CreatedAt  string
	ExpiresAt  string
	RetiredAt  string
}{
	Kid:        "jwt_keys.kid",
	PrivateKey: "jwt_keys.private_key",
	PublicKey:  "jwt_keys.public_key",
	Status:     "jwt_keys.status",
	CreatedAt:  "jwt_keys.created_at",
	ExpiresAt:  "jwt_keys.expires_at",
	RetiredAt:  "jwt_keys.retired_at",
}

// Generated where

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var JWTKeyWhere = struct {
	Kid        whereHelperstring
	PrivateKey whereHelperstring
	PublicKey  whereHelperstring
	Status     whereHelperstring
	CreatedAt  whereHelpertime_Time
	ExpiresAt  whereHelpernull_Time
	RetiredAt  whereHelpernull_Time
}{
	Kid:        whereHelperstring{field: "\"schema_identity\".\"jwt_keys\".\"kid\""},
	PrivateKey: whereHelperstring{field: "\"schema_identity\".\"jwt_keys\".\"private_key\""},
	PublicKey:  whereHelperstring{field: "\"schema_identity\".\"jwt_keys\".\"public_key\""},
	Status:     whereHelperstring{field: "\"schema_identity\".\"jwt_keys\".\"status\""},
	CreatedAt:  whereHelpertime_Time{field: "\"schema_identity\".\"jwt_keys\".\"created_at\""},
	ExpiresAt:  whereHelpernull_Time{field: "\"schema_identity\".\"jwt_keys\".\"expires_at\""},
	RetiredAt:  whereHelpernull_Time{field: "\"schema_identity\".\"jwt_keys\".\"retired_at\""},
}

// JWTKeyRels is where relationship names are stored.
var JWTKeyRels = struct {
}{}

// jwtKeyR is where relationships are stored.
type jwtKeyR struct {
}

// NewStruct creates a new relationship struct
func (*jwtKeyR) NewStruct() *jwtKeyR {
	return &jwtKeyR{}
}

// jwtKeyL is where Load methods for each relationship are stored.
type jwtKeyL struct{}

var (
	jwtKeyAllColumns            = []string{"kid", "private_key", "public_key", "status", "created_at", "expires_at", "retired_at"}
	jwtKeyColumnsWithoutDefault = []string{"kid", "private_key", "public_key"}
	jwtKeyColumnsWithDefault    = []string{"status", "created_at", "expires_at", "retired_at"}
	jwtKeyPrimaryKeyColumns     = []string{"kid"}
	jwtKeyGeneratedColumns      = []string{}
)

type (
	// JWTKeySlice is an alias for a slice of pointers to JWTKey.
	// This should almost always be used instead of []JWTKey.
	JWTKeySlice []*JWTKey
	// JWTKeyHook is the signature for custom JWTKey hook methods
	JWTKeyHook func(context.Context, boil.ContextExecutor, *JWTKey) error

	jwtKeyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	jwtKeyType                 = reflect.TypeOf(&JWTKey{})
	jwtKeyMapping              = queries.MakeStructMapping(jwtKeyType)
	jwtKeyPrimaryKeyMapping, _ = queries.BindMapping(jwtKeyType, jwtKeyMapping, jwtKeyPrimaryKeyColumns)
	jwtKeyInsertCacheMut       sync.RWMutex
	jwtKeyInsertCache          = make(map[string]insertCache)
	jwtKeyUpdateCacheMut       sync.RWMutex
	jwtKeyUpdateCache          = make(map[string]updateCache)
	jwtKeyUpsertCacheMut       sync.RWMutex
	jwtKeyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var jwtKeyAfterSelectMu sync.Mutex
var jwtKeyAfterSelectHooks []JWTKeyHook

var jwtKeyBeforeInsertMu sync.Mutex
var jwtKeyBeforeInsertHooks []JWTKeyHook
var jwtKeyAfterInsertMu sync.Mutex
var jwtKeyAfterInsertHooks []JWTKeyHook

var jwtKeyBeforeUpdateMu sync.Mutex
var jwtKeyBeforeUpdateHooks []JWTKeyHook
var jwtKeyAfterUpdateMu sync.Mutex
var jwtKeyAfterUpdateHooks []JWTKeyHook

var jwtKeyBeforeDeleteMu sync.Mutex
var jwtKeyBeforeDeleteHooks []JWTKeyHook
var jwtKeyAfterDeleteMu sync.Mutex
var jwtKeyAfterDeleteHooks []JWTKeyHook

var jwtKeyBeforeUpsertMu sync.Mutex
var jwtKeyBeforeUpsertHooks []JWTKeyHook
var jwtKeyAfterUpsertMu sync.Mutex
var jwtKeyAfterUpsertHooks []JWTKeyHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *JWTKey) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jwtKeyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *JWTKey) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jwtKeyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *JWTKey) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jwtKeyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *JWTKey) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jwtKeyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *JWTKey) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jwtKeyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *JWTKey) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jwtKeyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *JWTKey) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jwtKeyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *JWTKey) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jwtKeyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *JWTKey) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jwtKeyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddJWTKeyHook registers your hook function for all future operations.
func AddJWTKeyHook(hookPoint boil.HookPoint, jwtKeyHook JWTKeyHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		jwtKeyAfterSelectMu.Lock()
		jwtKeyAfterSelectHooks = append(jwtKeyAfterSelectHooks, jwtKeyHook)
		jwtKeyAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		jwtKeyBeforeInsertMu.Lock()
		jwtKeyBeforeInsertHooks = append(jwtKeyBeforeInsertHooks, jwtKeyHook)
		jwtKeyBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		jwtKeyAfterInsertMu.Lock()
		jwtKeyAfterInsertHooks = append(jwtKeyAfterInsertHooks, jwtKeyHook)
		jwtKeyAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		jwtKeyBeforeUpdateMu.Lock()
		jwtKeyBeforeUpdateHooks = append(jwtKeyBeforeUpdateHooks, jwtKeyHook)
		jwtKeyBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		jwtKeyAfterUpdateMu.Lock()
		jwtKeyAfterUpdateHooks = append(jwtKeyAfterUpdateHooks, jwtKeyHook)
		jwtKeyAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		jwtKeyBeforeDeleteMu.Lock()
		jwtKeyBeforeDeleteHooks = append(jwtKeyBeforeDeleteHooks, jwtKeyHook)
		jwtKeyBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		jwtKeyAfterDeleteMu.Lock()
		jwtKeyAfterDeleteHooks = append(jwtKeyAfterDeleteHooks, jwtKeyHook)
		jwtKeyAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		jwtKeyBeforeUpsertMu.Lock()
		jwtKeyBeforeUpsertHooks = append(jwtKeyBeforeUpsertHooks, jwtKeyHook)
		jwtKeyBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		jwtKeyAfterUpsertMu.Lock()
		jwtKeyAfterUpsertHooks = append(jwtKeyAfterUpsertHooks, jwtKeyHook)
		jwtKeyAfterUpsertMu.Unlock()
	}
}

// One returns a single jwtKey record from the query.
func (q jwtKeyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*JWTKey, error) {
	o := &JWTKey{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for jwt_keys")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all JWTKey records from the query.
func (q jwtKeyQuery) All(ctx context.Context, exec boil.ContextExecutor) (JWTKeySlice, error) {
	var o []*JWTKey

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to JWTKey slice")
	}

	if len(jwtKeyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all JWTKey records in the query.
func (q jwtKeyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count jwt_keys rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q jwtKeyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if jwt_keys exists")
	}

	return count > 0, nil
}

// JWTKeys retrieves all the records using an executor.
func JWTKeys(mods ...qm.QueryMod) jwtKeyQuery {
	mods = append(mods, qm.From("\"schema_identity\".\"jwt_keys\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"schema_identity\".\"jwt_keys\".*"})
	}

	return jwtKeyQuery{q}
}

// FindJWTKey retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindJWTKey(ctx context.Context, exec boil.ContextExecutor, kid string, selectCols ...string) (*JWTKey, error) {
	jwtKeyObj := &JWTKey{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"schema_identity\".\"jwt_keys\" where \"kid\"=$1", sel,
	)

	q := queries.Raw(query, kid)

	err := q.Bind(ctx, exec, jwtKeyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from jwt_keys")
	}

	if err = jwtKeyObj.doAfterSelectHooks(ctx, exec); err != nil {
		return jwtKeyObj, err
	}

	return jwtKeyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *JWTKey) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no jwt_keys provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(jwtKeyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	jwtKeyInsertCacheMut.RLock()
	cache, cached := jwtKeyInsertCache[key]
	jwtKeyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			jwtKeyAllColumns,
			jwtKeyColumnsWithDefault,
			jwtKeyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(jwtKeyType, jwtKeyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(jwtKeyType, jwtKeyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"schema_identity\".\"jwt_keys\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"schema_identity\".\"jwt_keys\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into jwt_keys")
	}

	if !cached {
		jwtKeyInsertCacheMut.Lock()
		jwtKeyInsertCache[key] = cache
		jwtKeyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the JWTKey.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *JWTKey) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	jwtKeyUpdateCacheMut.RLock()
	cache, cached := jwtKeyUpdateCache[key]
	jwtKeyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			jwtKeyAllColumns,
			jwtKeyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update jwt_keys, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"schema_identity\".\"jwt_keys\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, jwtKeyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(jwtKeyType, jwtKeyMapping, append(wl, jwtKeyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update jwt_keys row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for jwt_keys")
	}

	if !cached {
		jwtKeyUpdateCacheMut.Lock()
		jwtKeyUpdateCache[key] = cache
		jwtKeyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q jwtKeyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for jwt_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for jwt_keys")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o JWTKeySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), jwtKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"schema_identity\".\"jwt_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, jwtKeyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in jwtKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all jwtKey")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *JWTKey) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no jwt_keys provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(jwtKeyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	jwtKeyUpsertCacheMut.RLock()
	cache, cached := jwtKeyUpsertCache[key]
	jwtKeyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			jwtKeyAllColumns,
			jwtKeyColumnsWithDefault,
			jwtKeyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			jwtKeyAllColumns,
			jwtKeyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert jwt_keys, could not build update column list")
		}

		ret := strmangle.SetComplement(jwtKeyAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(jwtKeyPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert jwt_keys, could not build conflict column list")
			}

			conflict = make([]string, len(jwtKeyPrimaryKeyColumns))
			copy(conflict, jwtKeyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"schema_identity\".\"jwt_keys\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(jwtKeyType, jwtKeyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(jwtKeyType, jwtKeyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert jwt_keys")
	}

	if !cached {
		jwtKeyUpsertCacheMut.Lock()
		jwtKeyUpsertCache[key] = cache
		jwtKeyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single JWTKey record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *JWTKey) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no JWTKey provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), jwtKeyPrimaryKeyMapping)
	sql := "DELETE FROM \"schema_identity\".\"jwt_keys\" WHERE \"kid\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from jwt_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for jwt_keys")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q jwtKeyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no jwtKeyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from jwt_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for jwt_keys")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o JWTKeySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(jwtKeyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), jwtKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"schema_identity\".\"jwt_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, jwtKeyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from jwtKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for jwt_keys")
	}

	if len(jwtKeyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *JWTKey) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindJWTKey(ctx, exec, o.Kid)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *JWTKeySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := JWTKeySlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), jwtKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"schema_identity\".\"jwt_keys\".* FROM \"schema_identity\".\"jwt_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, jwtKeyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in JWTKeySlice")
	}

	*o = slice

	return nil
}

// JWTKeyExists checks if the JWTKey row exists.
func JWTKeyExists(ctx context.Context, exec boil.ContextExecutor, kid string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"schema_identity\".\"jwt_keys\" where \"kid\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, kid)
	}
	row := exec.QueryRowContext(ctx, sql, kid)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if jwt_keys exists")
	}

	return exists, nil
}

// Exists checks if the JWTKey row exists.
func (o *JWTKey) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return JWTKeyExists(ctx, exec, o.Kid)
}
